services:
  - type: web
    name: woon-radar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
