services:
  - type: web
    name: woon-radar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production

  - type: cron
    name: woonradar-scraper
    env: python
    schedule: "0 */4 * * *"
    command: python scraper.py
