name: Run Scraper Daily

on:
  schedule:
    - cron: '0 6 * * *'  # Dagelijks om 06:00 's ochtends UTC
  workflow_dispatch:      # Handmatig starten via GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated data.json
        run: |
          if test -f "data.json"; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add data.json
            git commit -m "Automated scrape update" || echo "No changes to commit"
            git push
          else
            echo "data.json not found. Skipping commit."
