name: Run Scraper Daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6,18 * * *'  # Dagelijks om 06:00 en 18:00 uur

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updated data.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f "static/data.json" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add static/data.json
            git commit -m "Automated scrape update" || echo "No changes to commit"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/JZWARTS/-woonradar-new.git
            git push origin HEAD:main
          fi
